/*
    ____    _         __  __ __  __ 
   / ___|  / \       |  \/  |  \/  |
   \___ \ / _ \ _____| |\/| | |\/| |
    ___) / ___ \_____| |  | | |  | |
   |____/_/   \_\    |_|  |_|_|  |_|            

    @File       admin.inc
    @Author     Neeko

    COPYRIGHT © 2021 - San Andreas Multimode
*/

#if defined _inc_admin
	#undef _inc_admin
#endif

#if defined _admin_included
	#endinput
#endif
#define _admin_included

#include <admin/core>
#include <admin/level1>
#include <admin/level5>