/*
    ____    _         __  __ __  __ 
   / ___|  / \       |  \/  |  \/  |
   \___ \ / _ \ _____| |\/| | |\/| |
    ___) / ___ \_____| |  | | |  | |
   |____/_/   \_\    |_|  |_|_|  |_|            

    @File       player.inc
    @Author     Neeko

    COPYRIGHT © 2021 - San Andreas Multimode
*/

#if defined _inc_player
	#undef _inc_player
#endif

#if defined _player_included
	#endinput
#endif
#define _player_included

#include <player/core>
#include <player/login>
#include <player/register>
#include <player/chat>
#include <player/cmd>